// <auto-generated />
namespace WhereTo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlaceAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlaceAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201503231911520_Place-Address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
